// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOhDCuT-6cZV-470Xh0cksVNnTx3_E1FE',
    appId: '1:170407269415:web:56f9f526373f9c8f0c6a02',
    messagingSenderId: '170407269415',
    projectId: 'uiproject-abde5',
    authDomain: 'uiproject-abde5.firebaseapp.com',
    storageBucket: 'uiproject-abde5.firebasestorage.app',
    measurementId: 'G-Z2NLVC19H8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4MChDF2LRTGXlKSoQc2dksEx6P1TqEP0',
    appId: '1:170407269415:android:169f21edccfb06c50c6a02',
    messagingSenderId: '170407269415',
    projectId: 'uiproject-abde5',
    storageBucket: 'uiproject-abde5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFqYW2B4EGYNf8vrJVi5GlUSkeKHrMr4M',
    appId: '1:170407269415:ios:4376f40c3faa2ffc0c6a02',
    messagingSenderId: '170407269415',
    projectId: 'uiproject-abde5',
    storageBucket: 'uiproject-abde5.firebasestorage.app',
    iosBundleId: 'com.example.uiProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFqYW2B4EGYNf8vrJVi5GlUSkeKHrMr4M',
    appId: '1:170407269415:ios:4376f40c3faa2ffc0c6a02',
    messagingSenderId: '170407269415',
    projectId: 'uiproject-abde5',
    storageBucket: 'uiproject-abde5.firebasestorage.app',
    iosBundleId: 'com.example.uiProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOhDCuT-6cZV-470Xh0cksVNnTx3_E1FE',
    appId: '1:170407269415:web:336211b3cd073b6b0c6a02',
    messagingSenderId: '170407269415',
    projectId: 'uiproject-abde5',
    authDomain: 'uiproject-abde5.firebaseapp.com',
    storageBucket: 'uiproject-abde5.firebasestorage.app',
    measurementId: 'G-LP29JZQR23',
  );
}
